In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']]
dependent

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [14]:
x_train

age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0     False       False
196    39  32.800         0     False       False
438    52  46.750         5     False       False
183    44  26.410         0     False       False
1298   33  27.455         2      True       False
...   ...     ...       ...       ...         ...
763    27  26.030         0      True       False
835    42  35.970         2      True       False
1216   40  25.080         0      True       False
559    19  35.530         0      True       False
684    33  18.500         1     False       False

[936 rows x 5 columns]

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [16]:
x_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [21]:
x_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid'],
              'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(x_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid']},
             verbose=3)

In [25]:
# print best parameter after tunng
# print(grid.best_params_)
re = grid.cv_results_
# print(re)
print("The r_value for best parameter{}:".format(grid.best_params_))

The r_value for best parameter{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:


In [27]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.200385      0.044785         0.065262        0.008180       10   
1        0.130687      0.029566         0.025586        0.006708       10   
2        0.191293      0.011634         0.035147        0.014824       10   
3        0.172448      0.023377         0.059670        0.006717       10   
4        0.125229      0.027763         0.021387        0.007934       10   
5        0.259167      0.148320         0.024985        0.010519       10   
6        1.277164      2.136784         0.063276        0.010933      100   
7        0.128530      0.002859         0.014407        0.001731      100   
8        0.152718      0.011092         0.032755        0.003382      100   
9        0.165245      0.021652         0.070371        0.006388      100   
10       0.163621      0.036462         0.014393        0.001019      100   
11       0.179888      0.038328         0.024385        0.009722      100   
12       0.169985      0.005110         0.073893        0.011258     1000   
13       0.180996      0.038055         0.018988        0.008758     1000   
14       0.217392      0.047377         0.044900        0.019041     1000   
15       0.177404      0.008919         0.076666        0.005846     1000   
16       0.176190      0.039024         0.026583        0.007468     1000   
17       0.189293      0.025258         0.038577        0.012069     1000   
18       0.183828      0.009222         0.065560        0.006941     2000   
19       0.308552      0.056094         0.017590        0.008703     2000   
20       0.177232      0.021992         0.028183        0.006760     2000   
21       0.195688      0.009666         0.062152        0.006136     2000   
22       0.270065      0.026019         0.019388        0.013297     2000   
23       0.270843      0.166255         0.024985        0.008871     2000   
24       0.233055      0.025655         0.065760        0.010697     3000   
25       0.495612      0.203269         0.034178        0.016462     3000   
26       0.191880      0.015392         0.035379        0.012266     3000   
27       0.211346      0.011554         0.072617        0.009750     3000   
28       0.645853      0.273711         0.013392        0.000799     3000   
29       0.202026      0.018386         0.042088        0.012617     3000   

   param_gamma param_kernel  \
0         auto          rbf   
1         auto         poly   
2         auto      sigmoid   
3        scale          rbf   
4        scale         poly   
5        scale      sigmoid   
6         auto          rbf   
7         auto         poly   
8         auto      sigmoid   
9        scale          rbf   
10       scale         poly   
11       scale      sigmoid   
12        auto          rbf   
13        auto         poly   
14        auto      sigmoid   
15       scale          rbf   
16       scale         poly   
17       scale      sigmoid   
18        auto          rbf   
19        auto         poly   
20        auto      sigmoid   
21       scale          rbf   
22       scale         poly   
23       scale      sigmoid   
24        auto          rbf   
25        auto         poly   
26        auto      sigmoid   
27       scale          rbf   
28       scale         poly   
29       scale      sigmoid   

                                               params  split0_test_score  \
0         {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}           0.004055   
1        {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}           0.056274   
2     {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}           0.049905   
3        {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}           0.004126   
4       {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}           0.054964   
5    {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}           0.049644   
6        {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}           0.300573   
7       {'C': 100, 'gamma': 'auto', 'kernel': 

In [29]:
grid_pred=grid.predict(x_test)
# print clssification reportz
from sklearn.metrics import r2_score
r_value=r2_score(y_test,grid_pred)
print("The r_value for best parameter{}:", format(grid.best_params_),r_value)

The r_value for best parameter{}: {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'} 0.8598930084494394


In [31]:
age=float(input("AGE:"))
bmi=float(input("BMI:"))
children=float(input("Children:"))
gender=int(input("Gender Male 0 or 1:"))
smoker=int(input("Smoker Yes 0 or 1 :"))

AGE: 32
BMI: 43
Children: 2
Gender Male 0 or 1: 0
Smoker Yes 0 or 1 : 1


In [35]:
Prediction=grid.predict([[age,bmi,children,gender,smoker]])
print("Future Predocion{}".format(Prediction))

Future Predocion[2291197.32936816]


In [37]:
Prediction=grid.predict([[32,43,2,0,1]])
Prediction

array([2291197.32936816])